# Profiles
SPRING_PROFILES_ACTIVE: prod

# Server
SERVER_PORT: ${SERVER_PORT}

# springdoc
SPRING_DOC_API_DOCS_ENABLED: false
SPRING_DOC_SWAGGER_UI_ENABLED: false

# cors
CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

# SOMQR P2P
SOMQR_P2P_SCHEME_IDENTIFIER: ${SOMQR_P2P_SCHEME_IDENTIFIER}
SOMQR_P2P_FI_NAME: ${SOMQR_P2P_FI_NAME}