# Profiles
SPRING_PROFILES_ACTIVE: dev

# Server
SERVER_PORT: 8080

# springdoc
SPRING_DOC_API_DOCS_ENABLED: true
SPRING_DOC_SWAGGER_UI_ENABLED: true

# cors
CORS_ALLOWED_ORIGINS: http://localhost:3000

# SOMQR P2P
SOMQR_P2P_SCHEME_IDENTIFIER: "01"
SOMQR_P2P_FI_NAME: "Galaxy International Bank"

# SOMQR P2M
SOMQR_P2M_FI_ACQUIRER_ID: "0011"
SOMQR_P2M_MNO_NETWORK_ID: "01"